buildVariable: true
buildStatic: true
includeSourceFixes: true # runs some metadata fixes for Google Fonts compatibility
autohintTTF: true
autohintOTF: false
sources:
  - Italic/Fraunces-Italic.designspace
  - Roman/Fraunces.designspace

# STAT names abbreviated to avoid problems in MS Word for Windows
# See Font Bakery name/family_and_style_max_length
stat:
  Fraunces[SOFT,WONK,opsz,wght].ttf:
    - name: Optical size
      tag: opsz
      values:
        - name: 9
          value: 9
        - name: 72
          value: 72
        - name: 144
          value: 144
    - name: Softness
      tag: SOFT
      values:
        - name: Sharp
          value: 0
        - name: Soft
          value: 50
        - name: SprSft
          value: 100
    - name: Weight
      tag: wght
      values:
        - name: Thin
          value: 100
        - name: Lght
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: SmBd
          value: 600
        - name: Bold
          value: 700
        - name: Blck
          value: 900
    - name: Wonky
      tag: WONK
      values:
        - name: NnWonk
          value: 0
        - name: Wonky
          value: 1
          flags: 2
    - name: Italic
      tag: ital
      values:
        - name: Roman
          value: 0
          linkedValue: 1
          flags: 2
  FrauncesItalic[SOFT,WONK,opsz,wght].ttf:
    - name: Optical size
      tag: opsz
      values:
        - name: 9
          value: 9
        - name: 72
          value: 72
        - name: 144
          value: 144
    - name: Softness
      tag: SOFT
      values:
        - name: Sharp
          value: 0
        - name: Soft
          value: 50
        - name: SprSft
          value: 100
    - name: Weight
      tag: wght
      values:
        - name: Thin
          value: 100
        - name: Lght
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: SmBd
          value: 600
        - name: Bold
          value: 700
        - name: Blck
          value: 900
    - name: Wonky
      tag: WONK
      values:
        - name: NnWonk
          value: 0
        - name: Wonky
          value: 1
          flags: 2
    - name: Italic
      tag: ital
      values:
        - name: Italic
          value: 1
