buildVariable: true
buildStatic: true
includeSourceFixes: true # runs some metadata fixes for Google Fonts compatibility
autohintTTF: true
autohintOTF: false
sources:
  - Italic/Fraunces-Italic.designspace
  - Roman/Fraunces.designspace
